name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Build step"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test step
        run: echo "running test cases"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy step
        run: echo "application deployed"
